In [1]:
2+2

4

In [2]:
number = 2
number + 3

5

In [3]:
import pandas as pd
import altair as alt

In [4]:
my_list = [2,4,6,8]

In [5]:
my_series = pd.Series(my_list)

In [6]:
my_series.sum()

20

In [7]:
my_series.max()

8

In [8]:
my_series.min()

2

In [9]:
my_series.describe()

count    4.000000
mean     5.000000
std      2.581989
min      2.000000
25%      3.500000
50%      5.000000
75%      6.500000
max      8.000000
dtype: float64

In [10]:
committee_list = pd.read_csv("https://raw.githubusercontent.com/california-civic-data-coalition/first-python-notebook/master/docs/_static/committees.csv")

In [11]:
committee_list.head()

,ocd_prop_id,calaccess_prop_id,ccdc_prop_id,prop_name,ccdc_committee_id,calaccess_committee_id,committee_name,committee_position
0,ocd-contest/b51dc64d-3562-4913-a190-69f5088c22a6,1376258,70,PROPOSITION 051 - SCHOOL BONDS. FUNDING FOR K-...,382,1374469,YES ON PROPOSITION 51 - CALIFORNIANS FOR QUALI...,SUPPORT
1,ocd-contest/b51dc64d-3562-4913-a190-69f5088c22a6,1376258,70,PROPOSITION 051 - SCHOOL BONDS. FUNDING FOR K-...,383,1220380,COMMUNITY COLLEGE FACILITY COALITION ISSUES CO...,SUPPORT
2,ocd-contest/b51dc64d-3562-4913-a190-69f5088c22a6,1376258,70,PROPOSITION 051 - SCHOOL BONDS. FUNDING FOR K-...,384,1282321,TORLAKSON'S INVEST IN CALIFORNIA A BALLOT MEAS...,SUPPORT
3,ocd-contest/b51dc64d-3562-4913-a190-69f5088c22a6,1376258,70,PROPOSITION 051 - SCHOOL BONDS. FUNDING FOR K-...,385,1382843,CALIFORNIA TAXPAYERS AND EDUCATORS OPPOSED TO ...,OPPOSE
4,ocd-contest/85990193-9d6f-4600-b8e7-bf1317841d82,1362198,71,PROPOSITION 052 - STATE FEES ON HOSPITALS. FED...,386,1362973,YES ON PROPOSITION 52 - A COALITION OF CALIFOR...,SUPPORT

In [12]:
committee_list.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102 entries, 0 to 101
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ocd_prop_id             102 non-null    object
 1   calaccess_prop_id       102 non-null    int64
 2   ccdc_prop_id            102 non-null    int64
 3   prop_name               102 non-null    object
 4   ccdc_committee_id       102 non-null    int64
 5   calaccess_committee_id  102 non-null    int64
 6   committee_name          102 non-null    object
 7   committee_position      102 non-null    object
dtypes: int64(4), object(4)
memory usage: 4.8+ KB

In [13]:
committee_list["prop_name"].value_counts().reset_index()

                                                index  prop_name
0   PROPOSITION 057 - CRIMINAL SENTENCES. JUVENILE...         13
1   PROPOSITION 056 - CIGARETTE TAX TO FUND HEALTH...         12
2   PROPOSITION 064- MARIJUANA LEGALIZATION. INITI...         11
3   PROPOSITION 066- DEATH PENALTY. PROCEDURES. IN...          9
4   PROPOSITION 055 - TAX EXTENSION TO FUND EDUCAT...          8
5   PROPOSITION 062- DEATH PENALTY. INITIATIVE STA...          7
6   PROPOSITION 067- REFERENDUM TO OVERTURN BAN ON...          7
7   PROPOSITION 059- SB 254 (CHAPTER 20, STATUTES ...          6
8   PROPOSITION 051 - SCHOOL BONDS. FUNDING FOR K-...          4
9   PROPOSITION 053 - REVENUE BONDS. STATEWIDE VOT...          4
10  PROPOSITION 058 - SB 1174 (CHAPTER 753, STATUT...          4
11  PROPOSITION 063- FIREARMS. AMMUNITION SALES. I...          4
12  PROPOSITION 054 - LEGISLATURE. LEGISLATION AND...          4
13  PROPOSITION 061- STATE PRESCRIPTION DRUG PURCH...          3
14  PROPOSITION 052 - STATE FEES ON HOSPITALS. FED...          3
15  PROPOSITION 060- ADULT FILMS. CONDOMS. HEALTH ...          2
16  PROPOSITION 065- CARRY-OUT BAGS. CHARGES. INIT...          1

In [14]:
my_prop = 'PROPOSITION 062- DEATH PENALTY. INITIATIVE STATUTE.'

In [15]:
my_committees = committee_list[committee_list.prop_name == my_prop]

In [16]:
my_committees.head()

,ocd_prop_id,calaccess_prop_id,ccdc_prop_id,prop_name,ccdc_committee_id,calaccess_committee_id,committee_name,committee_position
63,ocd-contest/cad98dde-416b-4cb3-8565-c1e8079511b3,1381268,81,PROPOSITION 062- DEATH PENALTY. INITIATIVE STA...,445,1380590,"YES ON 62, NO ON 66. REPLACE THE COSTLY, FAILE...",SUPPORT
64,ocd-contest/cad98dde-416b-4cb3-8565-c1e8079511b3,1381268,81,PROPOSITION 062- DEATH PENALTY. INITIATIVE STA...,446,1302403,CALIFORNIA CORRECTIONAL PEACE OFFICERS ASSOCIA...,OPPOSE
65,ocd-contest/cad98dde-416b-4cb3-8565-c1e8079511b3,1381268,81,PROPOSITION 062- DEATH PENALTY. INITIATIVE STA...,447,1346266,"CALIFORNIANS TO MEND, NOT END, THE DEATH PENAL...",OPPOSE
66,ocd-contest/cad98dde-416b-4cb3-8565-c1e8079511b3,1381268,81,PROPOSITION 062- DEATH PENALTY. INITIATIVE STA...,448,1391170,"MILLION VOTER PROJECT ACTION FUND - YES ON 55,...",SUPPORT
67,ocd-contest/cad98dde-416b-4cb3-8565-c1e8079511b3,1381268,81,PROPOSITION 062- DEATH PENALTY. INITIATIVE STA...,449,1385745,FUND FOR POLICY REFORM (NONPROFIT 501(C)(4)),SUPPORT

In [17]:
my_committees.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7 entries, 63 to 69
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ocd_prop_id             7 non-null      object
 1   calaccess_prop_id       7 non-null      int64
 2   ccdc_prop_id            7 non-null      int64
 3   prop_name               7 non-null      object
 4   ccdc_committee_id       7 non-null      int64
 5   calaccess_committee_id  7 non-null      int64
 6   committee_name          7 non-null      object
 7   committee_position      7 non-null      object
dtypes: int64(4), object(4)
memory usage: 392.0+ bytes

In [18]:
contrib_list = pd.read_csv("https://raw.githubusercontent.com/california-civic-data-coalition/first-python-notebook/master/docs/_static/contributions.csv")

In [19]:
contrib_list.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56379 entries, 0 to 56378
Data columns (total 13 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   calaccess_committee_id        56379 non-null  int64
 1   committee_name                56379 non-null  object
 2   calaccess_filing_id           56379 non-null  int64
 3   date_received                 56379 non-null  object
 4   contributor_lastname          56375 non-null  object
 5   contributor_firstname         53411 non-null  object
 6   contributor_city              56369 non-null  object
 7   contributor_state             56363 non-null  object
 8   contributor_zip               56366 non-null  object
 9   contributor_employer          48572 non-null  object
 10  contributor_occupation        53273 non-null  object
 11  contributor_is_self_employed  56379 non-null  bool
 12  amount                        56379 non-null  float64
dtypes: bool(1), float64(1), int64(2), object(9)
memory usage: 3.3+ MB

In [20]:
committee_list.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102 entries, 0 to 101
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ocd_prop_id             102 non-null    object
 1   calaccess_prop_id       102 non-null    int64
 2   ccdc_prop_id            102 non-null    int64
 3   prop_name               102 non-null    object
 4   ccdc_committee_id       102 non-null    int64
 5   calaccess_committee_id  102 non-null    int64
 6   committee_name          102 non-null    object
 7   committee_position      102 non-null    object
dtypes: int64(4), object(4)
memory usage: 4.8+ KB

In [21]:
merged = pd.merge(my_committees, contrib_list, on="calaccess_committee_id")

In [22]:
merged.head()

,ocd_prop_id,calaccess_prop_id,ccdc_prop_id,prop_name,ccdc_committee_id,calaccess_committee_id,committee_name_x,committee_position,committee_name_y,calaccess_filing_id,date_received,contributor_lastname,contributor_firstname,contributor_city,contributor_state,contributor_zip,contributor_employer,contributor_occupation,contributor_is_self_employed,amount
0,ocd-contest/cad98dde-416b-4cb3-8565-c1e8079511b3,1381268,81,PROPOSITION 062- DEATH PENALTY. INITIATIVE STA...,445,1380590,"YES ON 62, NO ON 66. REPLACE THE COSTLY, FAILE...",SUPPORT,"YES ON 62, NO ON 66. REPLACE THE COSTLY, FAILE...",2012950,2015-12-15,ALEXANDER,SUZI,SAN FRANCISCO,CA,94107,"ROBBINS GELLER RUDMAN & DOWD, LLP",ATTORNEY,False,100.0
1,ocd-contest/cad98dde-416b-4cb3-8565-c1e8079511b3,1381268,81,PROPOSITION 062- DEATH PENALTY. INITIATIVE STA...,445,1380590,"YES ON 62, NO ON 66. REPLACE THE COSTLY, FAILE...",SUPPORT,"YES ON 62, NO ON 66. REPLACE THE COSTLY, FAILE...",2012950,2015-12-08,ALLEN,GARLAND,SANTA MONICA,CA,90403,LAW OFFICE OF GARLAND ALLEN,ATTORNEY,False,1500.0
2,ocd-contest/cad98dde-416b-4cb3-8565-c1e8079511b3,1381268,81,PROPOSITION 062- DEATH PENALTY. INITIATIVE STA...,445,1380590,"YES ON 62, NO ON 66. REPLACE THE COSTLY, FAILE...",SUPPORT,"YES ON 62, NO ON 66. REPLACE THE COSTLY, FAILE...",2012950,2015-12-14,ANDREWS,KATHRYN,EL CERRITO,CA,94530,"KATHRYN ANDREWS, ATTORNEY AT LAW",ATTORNEY,False,100.0
3,ocd-contest/cad98dde-416b-4cb3-8565-c1e8079511b3,1381268,81,PROPOSITION 062- DEATH PENALTY. INITIATIVE STA...,445,1380590,"YES ON 62, NO ON 66. REPLACE THE COSTLY, FAILE...",SUPPORT,"YES ON 62, NO ON 66. REPLACE THE COSTLY, FAILE...",2012950,2015-12-15,BACON,ROBERT,OAKLAND,CA,94610,"ROBERT D. BACON, ATTORNEY AT LAW",ATTORNEY,False,750.0
4,ocd-contest/cad98dde-416b-4cb3-8565-c1e8079511b3,1381268,81,PROPOSITION 062- DEATH PENALTY. INITIATIVE STA...,445,1380590,"YES ON 62, NO ON 66. REPLACE THE COSTLY, FAILE...",SUPPORT,"YES ON 62, NO ON 66. REPLACE THE COSTLY, FAILE...",2012950,2015-12-14,BAYLESS,RICHARD,FREMONT,CA,94539,NONE,RETIRED,False,100.0

In [23]:
merged.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 34442 entries, 0 to 34441
Data columns (total 20 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   ocd_prop_id                   34442 non-null  object
 1   calaccess_prop_id             34442 non-null  int64
 2   ccdc_prop_id                  34442 non-null  int64
 3   prop_name                     34442 non-null  object
 4   ccdc_committee_id             34442 non-null  int64
 5   calaccess_committee_id        34442 non-null  int64
 6   committee_name_x              34442 non-null  object
 7   committee_position            34442 non-null  object
 8   committee_name_y              34442 non-null  object
 9   calaccess_filing_id           34442 non-null  int64
 10  date_received                 34442 non-null  object
 11  contributor_lastname          34438 non-null  object
 12  contributor_firstname         33920 non-null  object
 13  contributor_city              34434 non-null  object
 14  contributor_state             34432 non-null  object
 15  contributor_zip               34432 non-null  object
 16  contributor_employer          33559 non-null  object
 17  contributor_occupation        33915 non-null  object
 18  contributor_is_self_employed  34442 non-null  bool
 19  amount                        34442 non-null  float64
dtypes: bool(1), float64(1), int64(5), object(13)
memory usage: 3.6+ MB

In [24]:
merged["amount"].sum()

32836678.18

In [25]:
merged["committee_position"].value_counts()

OPPOSE     29633
SUPPORT     4809
Name: committee_position, dtype: int64

In [26]:
support = merged[merged["committee_position"] == 'SUPPORT']

In [27]:
oppose = merged[merged["committee_position"] == 'OPPOSE']

In [28]:
oppose.amount.sum()

16836069.81

In [29]:
support.amount.sum()

16000608.370000001

In [30]:
support["amount"].sum()/merged["amount"].sum()

0.4872785329347221

In [31]:
merged.sort_values("amount",ascending=False).head()

,ocd_prop_id,calaccess_prop_id,ccdc_prop_id,prop_name,ccdc_committee_id,calaccess_committee_id,committee_name_x,committee_position,committee_name_y,calaccess_filing_id,date_received,contributor_lastname,contributor_firstname,contributor_city,contributor_state,contributor_zip,contributor_employer,contributor_occupation,contributor_is_self_employed,amount
33745,ocd-contest/cad98dde-416b-4cb3-8565-c1e8079511b3,1381268,81,PROPOSITION 062- DEATH PENALTY. INITIATIVE STA...,449,1385745,FUND FOR POLICY REFORM (NONPROFIT 501(C)(4)),SUPPORT,FUND FOR POLICY REFORM (NONPROFIT 501(C)(4)),2082414,2016-09-15,FUND FOR POLICY REFORM,NaN,WILMINGTON,DE,19809,NaN,NaN,False,1970000.0
33737,ocd-contest/cad98dde-416b-4cb3-8565-c1e8079511b3,1381268,81,PROPOSITION 062- DEATH PENALTY. INITIATIVE STA...,448,1391170,"MILLION VOTER PROJECT ACTION FUND - YES ON 55,...",SUPPORT,"MILLION VOTER PROJECT ACTION FUND - YES ON 55,...",2098635,2016-10-13,STEYER,THOMAS,SAN FRANCISCO,CA,94104-4919,FARALLON CAPITAL,FOUNDER,False,1500000.0
33746,ocd-contest/cad98dde-416b-4cb3-8565-c1e8079511b3,1381268,81,PROPOSITION 062- DEATH PENALTY. INITIATIVE STA...,449,1385745,FUND FOR POLICY REFORM (NONPROFIT 501(C)(4)),SUPPORT,FUND FOR POLICY REFORM (NONPROFIT 501(C)(4)),2096507,2016-09-27,FUND FOR POLICY REFORM,NaN,WILMINGTON,DE,19809,NaN,NaN,False,1403000.0
33744,ocd-contest/cad98dde-416b-4cb3-8565-c1e8079511b3,1381268,81,PROPOSITION 062- DEATH PENALTY. INITIATIVE STA...,449,1385745,FUND FOR POLICY REFORM (NONPROFIT 501(C)(4)),SUPPORT,FUND FOR POLICY REFORM (NONPROFIT 501(C)(4)),2082414,2016-07-07,FUND FOR POLICY REFORM,NaN,WILMINGTON,DE,19809,NaN,NaN,False,1000000.0
33742,ocd-contest/cad98dde-416b-4cb3-8565-c1e8079511b3,1381268,81,PROPOSITION 062- DEATH PENALTY. INITIATIVE STA...,449,1385745,FUND FOR POLICY REFORM (NONPROFIT 501(C)(4)),SUPPORT,FUND FOR POLICY REFORM (NONPROFIT 501(C)(4)),2057298,2016-05-03,FUND FOR POLICY REFORM,NaN,WILMINGTON,DE,19809,NaN,NaN,False,550000.0

In [32]:
support.sort_values("amount",ascending=False).head()

,ocd_prop_id,calaccess_prop_id,ccdc_prop_id,prop_name,ccdc_committee_id,calaccess_committee_id,committee_name_x,committee_position,committee_name_y,calaccess_filing_id,date_received,contributor_lastname,contributor_firstname,contributor_city,contributor_state,contributor_zip,contributor_employer,contributor_occupation,contributor_is_self_employed,amount
33745,ocd-contest/cad98dde-416b-4cb3-8565-c1e8079511b3,1381268,81,PROPOSITION 062- DEATH PENALTY. INITIATIVE STA...,449,1385745,FUND FOR POLICY REFORM (NONPROFIT 501(C)(4)),SUPPORT,FUND FOR POLICY REFORM (NONPROFIT 501(C)(4)),2082414,2016-09-15,FUND FOR POLICY REFORM,NaN,WILMINGTON,DE,19809,NaN,NaN,False,1970000.0
33737,ocd-contest/cad98dde-416b-4cb3-8565-c1e8079511b3,1381268,81,PROPOSITION 062- DEATH PENALTY. INITIATIVE STA...,448,1391170,"MILLION VOTER PROJECT ACTION FUND - YES ON 55,...",SUPPORT,"MILLION VOTER PROJECT ACTION FUND - YES ON 55,...",2098635,2016-10-13,STEYER,THOMAS,SAN FRANCISCO,CA,94104-4919,FARALLON CAPITAL,FOUNDER,False,1500000.0
33746,ocd-contest/cad98dde-416b-4cb3-8565-c1e8079511b3,1381268,81,PROPOSITION 062- DEATH PENALTY. INITIATIVE STA...,449,1385745,FUND FOR POLICY REFORM (NONPROFIT 501(C)(4)),SUPPORT,FUND FOR POLICY REFORM (NONPROFIT 501(C)(4)),2096507,2016-09-27,FUND FOR POLICY REFORM,NaN,WILMINGTON,DE,19809,NaN,NaN,False,1403000.0
33744,ocd-contest/cad98dde-416b-4cb3-8565-c1e8079511b3,1381268,81,PROPOSITION 062- DEATH PENALTY. INITIATIVE STA...,449,1385745,FUND FOR POLICY REFORM (NONPROFIT 501(C)(4)),SUPPORT,FUND FOR POLICY REFORM (NONPROFIT 501(C)(4)),2082414,2016-07-07,FUND FOR POLICY REFORM,NaN,WILMINGTON,DE,19809,NaN,NaN,False,1000000.0
33742,ocd-contest/cad98dde-416b-4cb3-8565-c1e8079511b3,1381268,81,PROPOSITION 062- DEATH PENALTY. INITIATIVE STA...,449,1385745,FUND FOR POLICY REFORM (NONPROFIT 501(C)(4)),SUPPORT,FUND FOR POLICY REFORM (NONPROFIT 501(C)(4)),2057298,2016-05-03,FUND FOR POLICY REFORM,NaN,WILMINGTON,DE,19809,NaN,NaN,False,550000.0

In [33]:
oppose.sort_values("amount",ascending=False).head()

,ocd_prop_id,calaccess_prop_id,ccdc_prop_id,prop_name,ccdc_committee_id,calaccess_committee_id,committee_name_x,committee_position,committee_name_y,calaccess_filing_id,date_received,contributor_lastname,contributor_firstname,contributor_city,contributor_state,contributor_zip,contributor_employer,contributor_occupation,contributor_is_self_employed,amount
33246,ocd-contest/cad98dde-416b-4cb3-8565-c1e8079511b3,1381268,81,PROPOSITION 062- DEATH PENALTY. INITIATIVE STA...,447,1346266,"CALIFORNIANS TO MEND, NOT END, THE DEATH PENAL...",OPPOSE,"CALIFORNIANS TO MEND, NOT END, THE DEATH PENAL...",2064651,2016-05-05,NICHOLAS III,HENRY T.,ALISO VIEJO,CA,92656,"HENRY T. NICHOLAS, III FOUNDATION / NICHOLAS E...",PHILANTHROPIST / BUSINESS EXECUTIVE,False,200000.0
33014,ocd-contest/cad98dde-416b-4cb3-8565-c1e8079511b3,1381268,81,PROPOSITION 062- DEATH PENALTY. INITIATIVE STA...,447,1346266,"CALIFORNIANS TO MEND, NOT END, THE DEATH PENAL...",OPPOSE,"CALIFORNIANS FOR JUSTICE AND PUBLIC SAFETY, NO...",2064651,2016-05-05,NICHOLAS III,HENRY T.,ALISO VIEJO,CA,92656,"HENRY T. NICHOLAS, III FOUNDATION / NICHOLAS E...",PHILANTHROPIST / BUSINESS EXECUTIVE,False,200000.0
33734,ocd-contest/cad98dde-416b-4cb3-8565-c1e8079511b3,1381268,81,PROPOSITION 062- DEATH PENALTY. INITIATIVE STA...,447,1346266,"CALIFORNIANS TO MEND, NOT END, THE DEATH PENAL...",OPPOSE,"CALIFORNIANS TO MEND, NOT END, THE DEATH PENAL...",2130372,2016-12-08,CALIFORNIA CORRECTIONAL PEACE OFFICERS ASSOCIA...,NaN,SACRAMENTO,CA,95814,NaN,NaN,False,125000.0
33696,ocd-contest/cad98dde-416b-4cb3-8565-c1e8079511b3,1381268,81,PROPOSITION 062- DEATH PENALTY. INITIATIVE STA...,447,1346266,"CALIFORNIANS TO MEND, NOT END, THE DEATH PENAL...",OPPOSE,"CALIFORNIANS FOR JUSTICE AND PUBLIC SAFETY, NO...",2130372,2016-12-08,CALIFORNIA CORRECTIONAL PEACE OFFICERS ASSOCIA...,NaN,SACRAMENTO,CA,95814,NaN,NaN,False,125000.0
32739,ocd-contest/cad98dde-416b-4cb3-8565-c1e8079511b3,1381268,81,PROPOSITION 062- DEATH PENALTY. INITIATIVE STA...,447,1346266,"CALIFORNIANS TO MEND, NOT END, THE DEATH PENAL...",OPPOSE,"CALIFORNIANS FOR JUSTICE AND PUBLIC SAFETY, NO...",2012262,2015-11-05,LOS ANGELES POLICE PROTECTIVE LEAGUE ISSUES PAC,NaN,SACRAMENTO,CA,95814,NaN,NaN,False,125000.0

In [34]:
merged.groupby("contributor_state")["amount"].sum()

contributor_state
AB    1.300000e+02
AK    5.000000e+02
AL    7.000000e+02
AZ    1.150250e+04
BC    2.100000e+02
CA    2.593895e+07
CO    9.950000e+02
CT    1.291500e+03
DC    5.009350e+05
DE    6.140550e+06
FL    3.690000e+03
GA    1.365000e+03
HI    9.725000e+02
IA    1.005000e+03
IL    2.056000e+04
IN    1.850000e+02
KS    4.000000e+02
KY    2.100000e+02
LA    3.500000e+02
MA    2.171100e+04
MD    4.135000e+03
ME    4.050000e+02
MI    2.800000e+02
MN    1.500000e+02
MO    5.250000e+02
MT    1.450000e+02
NB    4.000000e+01
NC    1.633000e+03
NE    3.250000e+02
NH    1.450000e+02
NJ    4.707500e+03
NM    1.050000e+03
NV    6.220000e+03
NY    8.125150e+04
OH    7.600000e+02
OK    1.750000e+02
OR    1.217400e+03
PA    1.975000e+03
RI    2.450000e+02
SC    1.800000e+02
SD    2.175000e+02
TN    1.630000e+03
TX    1.313500e+04
UT    2.011000e+04
VA    2.889000e+03
VT    9.550000e+02
WA    4.424500e+04
WI    2.700000e+02
Name: amount, dtype: float64

In [35]:
merged.groupby("contributor_state")["amount"].sum().reset_index().sort_values("amount",ascending=False)

   contributor_state        amount
5                 CA  2.593895e+07
9                 DE  6.140550e+06
8                 DC  5.009350e+05
33                NY  8.125150e+04
46                WA  4.424500e+04
19                MA  2.171100e+04
14                IL  2.056000e+04
43                UT  2.011000e+04
42                TX  1.313500e+04
3                 AZ  1.150250e+04
32                NV  6.220000e+03
30                NJ  4.707500e+03
20                MD  4.135000e+03
10                FL  3.690000e+03
44                VA  2.889000e+03
37                PA  1.975000e+03
27                NC  1.633000e+03
41                TN  1.630000e+03
11                GA  1.365000e+03
7                 CT  1.291500e+03
36                OR  1.217400e+03
31                NM  1.050000e+03
13                IA  1.005000e+03
6                 CO  9.950000e+02
12                HI  9.725000e+02
45                VT  9.550000e+02
34                OH  7.600000e+02
2                 AL  7.000000e+02
24                MO  5.250000e+02
1                 AK  5.000000e+02
21                ME  4.050000e+02
16                KS  4.000000e+02
18                LA  3.500000e+02
28                NE  3.250000e+02
22                MI  2.800000e+02
47                WI  2.700000e+02
38                RI  2.450000e+02
40                SD  2.175000e+02
17                KY  2.100000e+02
4                 BC  2.100000e+02
15                IN  1.850000e+02
39                SC  1.800000e+02
35                OK  1.750000e+02
23                MN  1.500000e+02
29                NH  1.450000e+02
25                MT  1.450000e+02
0                 AB  1.300000e+02
26                NB  4.000000e+01

In [36]:
merged.groupby(["contributor_firstname","contributor_lastname","committee_position"])["amount"].sum().reset_index().sort_values("amount",ascending=False)

      contributor_firstname contributor_lastname committee_position     amount
28396                THOMAS               STEYER            SUPPORT  1750000.0
21812              NICHOLAS              MCKEOWN            SUPPORT  1500000.0
23740                  REED             HASTINGS            SUPPORT  1000000.0
22511                  PAUL               GRAHAM            SUPPORT   500000.0
17405               L. JOHN                DOERR            SUPPORT   500000.0
...                     ...                  ...                ...        ...
8102                 EDWARD              DEERING            SUPPORT       10.0
21525                MORLEY                 KAHN            SUPPORT        9.0
27666                STEVEN                HODEL            SUPPORT        5.0
6986                 DEBBIE               MYTELS            SUPPORT        5.0
29966               WILLIAM              BABBITT            SUPPORT        0.0

[30440 rows x 4 columns]

In [37]:
support.groupby(["contributor_firstname","contributor_lastname"])["amount"].sum().reset_index().sort_values("amount",ascending=False)

     contributor_firstname contributor_lastname     amount
1815                THOMAS               STEYER  1750000.0
1385              NICHOLAS              MCKEOWN  1500000.0
1516                  REED             HASTINGS  1000000.0
1058               L. JOHN                DOERR   500000.0
1439                  PAUL               GRAHAM   500000.0
...                    ...                  ...        ...
439                 DENNIS           MCLAUGHLIN       10.0
1342                MORLEY                 KAHN        9.0
415                 DEBBIE               MYTELS        5.0
1733                STEVEN                HODEL        5.0
1893               WILLIAM              BABBITT        0.0

[1925 rows x 3 columns]

In [38]:
oppose.groupby(["contributor_firstname","contributor_lastname"])["amount"].sum().reset_index().sort_values("amount",ascending=False)

      contributor_firstname contributor_lastname    amount
10519              HENRY T.         NICHOLAS III  400000.0
15205                 JULIE             MOTAMEDI  350000.0
26206                 SUSAN                GROFF  160000.0
6612             DEBRA JANE           STEINHARDT  100000.0
10280                 H. F.        BOECKMANN, II  100000.0
...                     ...                  ...       ...
19035               MICHAEL                MAHER     200.0
3738           CATHERINE J.                  GAY     200.0
705            ALEXANDER A.                MANOS     200.0
23458             ROBERT S.               KOWELL     200.0
3928                CHARLES               LITZEN     200.0

[28515 rows x 3 columns]

In [39]:
merged.fillna("").groupby(["contributor_firstname","contributor_lastname","committee_position"])["amount"].sum().reset_index().sort_values("amount",ascending=False)

,contributor_firstname,contributor_lastname,committee_position,amount
59,,FUND FOR POLICY REFORM,SUPPORT,6140000.0
28596,THOMAS,STEYER,SUPPORT,1750000.0
22012,NICHOLAS,MCKEOWN,SUPPORT,1500000.0
23940,REED,HASTINGS,SUPPORT,1000000.0
24,,CALIFORNIA CORRECTIONAL PEACE OFFICERS ASSOCIA...,OPPOSE,650000.0
...,...,...,...,...
14012,JIM,PATRICOLA,SUPPORT,10.0
21725,MORLEY,KAHN,SUPPORT,9.0
27866,STEVEN,HODEL,SUPPORT,5.0
7185,DEBBIE,MYTELS,SUPPORT,5.0
30166,WILLIAM,BABBITT,SUPPORT,0.0

In [40]:
top_supporters = support.fillna("").groupby(
    ["contributor_firstname", "contributor_lastname"]
).amount.sum().reset_index().sort_values("amount", ascending=False).head(10)

In [41]:
top_supporters.head(10)

,contributor_firstname,contributor_lastname,amount
15,,FUND FOR POLICY REFORM,6140000.0
1854,THOMAS,STEYER,1750000.0
1424,NICHOLAS,MCKEOWN,1500000.0
1555,REED,HASTINGS,1000000.0
19,,"LAURENE POWELL JOBS, INCLUDING EMERSON COLLECT...",600000.0
1478,PAUL,GRAHAM,500000.0
1097,L. JOHN,DOERR,500000.0
25,,OPEN SOCIETY POLICY CENTER INC.,500000.0
23,,NEXTGEN CALIFORNIA,250000.0
1626,ROBERT ALAN,EUSTACE,175000.0

In [42]:
alt.Chart(top_supporters).mark_bar().encode(
    x="contributor_lastname",
    y="amount"
)

alt.Chart(...)

In [43]:
alt.Chart(top_supporters).mark_bar().encode(
    y="contributor_lastname",
    x="amount"
)

alt.Chart(...)

In [44]:
alt.Chart(top_supporters.head(5)).mark_bar().encode(
    x="contributor_lastname",
    y="amount"
)

alt.Chart(...)

In [ ]:
top_supporters.head(5).to_csv("top_supporters.csv")